name: Docker Image Deployment to Azure WebApp
on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
env:
  DOCKER_IMAGE_NAME: 'aspdotnetdocker'
  AZURE_WEB_APP: 'aspdotnetdockerapp'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USER1 }} 
        password: ${{ secrets.DOCKER_PASSWORD1 }} 
        login-server: vsaspdotnetcore.azurecr.io
   
   
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag '${{env.DOCKER_IMAGE_NAME}}':${{ github.sha }}
    - name: Tag the Docker image
      run: docker tag '${{env.DOCKER_IMAGE_NAME}}':${{ github.sha }} vsaspdotnetcore.azurecr.io/'${{env.DOCKER_IMAGE_NAME}}':${{ github.sha }}
    - name: Push the Docker image
      run: docker push vsaspdotnetcore.azurecr.io/'${{env.DOCKER_IMAGE_NAME}}':${{ github.sha }}
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS1 }}     
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
       app-name: '${{env.AZURE_WEB_APP}}'
       images: vsaspdotnetcore.azurecr.io/'${{env.DOCKER_IMAGE_NAME}}':${{ github.sha }}



      
