name: Docker Image Deployment to Azure WebApp
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOCKER_IMAGE_NAME: 'vsaspdo'
  AZURE_WEB_APP: 'vsaspdotnetdocker'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USER }} 
        password: ${{ secrets.DOCKER_PASSWORD }} 
        login-server: edtghe.azurecr.io
   
   
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag '${{env.DOCKER_IMAGE_NAME}}':latest
    - name: Tag the Docker image
      run: docker tag '${{env.DOCKER_IMAGE_NAME}}':latest edtghe.azurecr.io/'${{env.DOCKER_IMAGE_NAME}}':latest
    - name: Push the Docker image
      run: docker push edtghe.azurecr.io/'${{env.DOCKER_IMAGE_NAME}}':latest
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}     
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
       app-name: '${{env.AZURE_WEB_APP}}'
       images: edtghe.azurecr.io/'${{env.DOCKER_IMAGE_NAME}}':latest



      
