name: Docker Image Deployment to Azure WebApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOCKER_IMAGE_NAME: 'vsaspdotnetcoreapp'
  AZURE_WEB_APP: 'vsaspnetcoreapp-docker-demo'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
         username: ${{ secrets.DOCKER_USER }} 
         password: ${{ secrets.DOCKER_PASSWORD }} 
         login-server: vsazurecr.azurecr.io
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag '${{env.DOCKER_IMAGE_NAME}}':latest
    - name: Tag the Docker image
      run: docker tag '${{env.DOCKER_IMAGE_NAME}}':latest vsazurecr.azurecr.io/'${{env.DOCKER_IMAGE_NAME}}':latest
    - name: Push the Docker image
      run: docker push vsazurecr.azurecr.io/'${{env.DOCKER_IMAGE_NAME}}':latest
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure WebApp Deployment
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: '${{env.AZURE_WEB_APP}}'
        # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
        images: vsazurecr.azurecr.io/'${{env.DOCKER_IMAGE_NAME}}':latest

      
